# Generated by Django 6.0.5 on 2026-05-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='examens.ecole')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
                'unique_together': {('nom', 'ecole')},
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mini_cours', models.TextField(blank=True, verbose_name='Mini cours')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='examens.filiere')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['-annee'],
                'unique_together': {('filiere', 'titre', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte de la question')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examens.epreuve')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500, verbose_name='Texte')),
                ('est_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='examens.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('terminee', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='comptes.eleve')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='examens.epreuve')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examens.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='examens.tentative')),
            ],
            options={
                'verbose_name': 'Réponse élève',
                'verbose_name_plural': 'Réponses élèves',
                'unique_together': {('tentative', 'question')},
            },
        ),
    ]
