# Generated by Django 6.0.4 on 2026-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ecoles/logos/', verbose_name='Logo'),
        ),
    ]
