# Generated by Django 6.0.5 on 2026-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_ecole_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Image'),
        ),
    ]
