# Generated by Django 6.0.4 on 2026-07-26 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcoursBlanc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('heure_debut', models.DateTimeField(verbose_name='Heure de début')),
                ('heure_fin', models.DateTimeField(verbose_name='Heure de fin')),
                ('nb_places_max', models.PositiveIntegerField(verbose_name='Nombre de places maximum')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('termine', 'Terminé')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('classement_publie', models.BooleanField(default=False, verbose_name='Classement publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concours_blancs', to='examens.ecole')),
            ],
            options={
                'verbose_name': 'Concours Blanc',
                'verbose_name_plural': 'Concours Blancs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du participant')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='examens.concoursblanc')),
            ],
            options={
                'verbose_name': 'Participant concours blanc',
                'verbose_name_plural': 'Participants concours blanc',
                'ordering': ['date_inscription'],
                'unique_together': {('concours', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='TentativeConcoursParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('terminee', models.BooleanField(default=False)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_concours', to='examens.epreuve')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='examens.participantconcours')),
            ],
            options={
                'verbose_name': 'Tentative concours participant',
                'verbose_name_plural': 'Tentatives concours participant',
                'unique_together': {('participant', 'epreuve')},
            },
        ),
        migrations.CreateModel(
            name='ConcoursBlancEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concours_epreuves', to='examens.concoursblanc')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves_concours', to='examens.epreuve')),
            ],
            options={
                'verbose_name': 'Épreuve du concours blanc',
                'verbose_name_plural': 'Épreuves du concours blanc',
                'ordering': ['ordre'],
                'unique_together': {('concours', 'epreuve'), ('concours', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='ReponseConcoursParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examens.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='examens.tentativeconcoursparticipant')),
            ],
            options={
                'verbose_name': 'Réponse concours participant',
                'verbose_name_plural': 'Réponses concours participant',
                'unique_together': {('tentative', 'question')},
            },
        ),
    ]
