# Generated by Django 6.0.4 on 2026-07-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0004_concoursblanc_participantconcours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeconcoursparticipant',
            name='revue',
            field=models.BooleanField(default=False, verbose_name='Revue'),
        ),
    ]
