# Generated by Django 6.0.4 on 2026-06-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code parrainage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_parrainage', to='comptes.eleve')),
            ],
            options={
                'verbose_name': 'Code parrainage',
                'verbose_name_plural': 'Codes parrainage',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('parrainage', 'Parrainage'), ('bonus', 'Bonus'), ('info', 'Information')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bonus_paye', models.BooleanField(default=False, verbose_name='Bonus payé')),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_recu', to='comptes.eleve')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainages_effectues', to='comptes.eleve')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'unique_together': {('parrain', 'filleul')},
            },
        ),
    ]
