# Generated by Django 6.0.5 on 2026-07-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_codeparrainage_notification_parrainage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_code', models.CharField(max_length=20)),
                ('nouveau_code', models.CharField(max_length=20)),
                ('migre', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_migre', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migration_code', to='comptes.eleve')),
            ],
            options={
                'verbose_name': "Migration code d'accès",
                'verbose_name_plural': "Migrations codes d'accès",
            },
        ),
    ]
